const WORKFLOW_STATUS = require('../constants/workflowStatus');
const ApiError = require('../utils/apiError');

const TRANSITION_RULES = {
  LEAD: {
    [WORKFLOW_STATUS.LEAD.NEW]: [
      WORKFLOW_STATUS.LEAD.CONTACTED,
      WORKFLOW_STATUS.LEAD.QUALIFIED,
      WORKFLOW_STATUS.LEAD.LOST
    ],
    [WORKFLOW_STATUS.LEAD.CONTACTED]: [
      WORKFLOW_STATUS.LEAD.FOLLOW_UP,
      WORKFLOW_STATUS.LEAD.QUALIFIED,
      WORKFLOW_STATUS.LEAD.LOST
    ],
    [WORKFLOW_STATUS.LEAD.FOLLOW_UP]: [
      WORKFLOW_STATUS.LEAD.FOLLOW_UP,
      WORKFLOW_STATUS.LEAD.QUALIFIED,
      WORKFLOW_STATUS.LEAD.LOST
    ],
    [WORKFLOW_STATUS.LEAD.QUALIFIED]: [
      WORKFLOW_STATUS.LEAD.CONVERTED,
      WORKFLOW_STATUS.LEAD.LOST
    ],
    [WORKFLOW_STATUS.LEAD.LOST]: [
      WORKFLOW_STATUS.LEAD.NEW
    ],
    [WORKFLOW_STATUS.LEAD.CONVERTED]: []
  },

  QUOTATION: {
    [WORKFLOW_STATUS.QUOTATION.DRAFT]: [
      WORKFLOW_STATUS.QUOTATION.PENDING_APPROVAL,
      WORKFLOW_STATUS.QUOTATION.SENT,
      WORKFLOW_STATUS.QUOTATION.ACCEPTED,
      WORKFLOW_STATUS.QUOTATION.LOST
    ],
    [WORKFLOW_STATUS.QUOTATION.PENDING_APPROVAL]: [
      WORKFLOW_STATUS.QUOTATION.APPROVED,
      WORKFLOW_STATUS.QUOTATION.REJECTED,
      WORKFLOW_STATUS.QUOTATION.DRAFT
    ],
    [WORKFLOW_STATUS.QUOTATION.APPROVED]: [
      WORKFLOW_STATUS.QUOTATION.SENT,
      WORKFLOW_STATUS.QUOTATION.ACCEPTED
    ],
    [WORKFLOW_STATUS.QUOTATION.REJECTED]: [
      WORKFLOW_STATUS.QUOTATION.DRAFT
    ],
    [WORKFLOW_STATUS.QUOTATION.SENT]: [
      WORKFLOW_STATUS.QUOTATION.NEGOTIATION,
      WORKFLOW_STATUS.QUOTATION.REVISED,
      WORKFLOW_STATUS.QUOTATION.ACCEPTED,
      WORKFLOW_STATUS.QUOTATION.EXPIRED,
      WORKFLOW_STATUS.QUOTATION.LOST
    ],
    [WORKFLOW_STATUS.QUOTATION.NEGOTIATION]: [
      WORKFLOW_STATUS.QUOTATION.REVISED,
      WORKFLOW_STATUS.QUOTATION.ACCEPTED,
      WORKFLOW_STATUS.QUOTATION.LOST
    ],
    [WORKFLOW_STATUS.QUOTATION.REVISED]: [
      WORKFLOW_STATUS.QUOTATION.PENDING_APPROVAL,
      WORKFLOW_STATUS.QUOTATION.SENT,
      WORKFLOW_STATUS.QUOTATION.ACCEPTED
    ],
    [WORKFLOW_STATUS.QUOTATION.ACCEPTED]: [],
    [WORKFLOW_STATUS.QUOTATION.EXPIRED]: [WORKFLOW_STATUS.QUOTATION.REVISED],
    [WORKFLOW_STATUS.QUOTATION.LOST]: []
  },

  CUSTOMER_PO: {
    [WORKFLOW_STATUS.CUSTOMER_PO.RECEIVED]: [
      WORKFLOW_STATUS.CUSTOMER_PO.PENDING_VERIFICATION
    ],
    [WORKFLOW_STATUS.CUSTOMER_PO.PENDING_VERIFICATION]: [
      WORKFLOW_STATUS.CUSTOMER_PO.VERIFIED,
      WORKFLOW_STATUS.CUSTOMER_PO.MISMATCH_HOLD,
      WORKFLOW_STATUS.CUSTOMER_PO.REJECTED
    ],
    [WORKFLOW_STATUS.CUSTOMER_PO.MISMATCH_HOLD]: [
      WORKFLOW_STATUS.CUSTOMER_PO.PENDING_VERIFICATION,
      WORKFLOW_STATUS.CUSTOMER_PO.VERIFIED,
      WORKFLOW_STATUS.CUSTOMER_PO.REJECTED
    ],
    [WORKFLOW_STATUS.CUSTOMER_PO.VERIFIED]: [],
    [WORKFLOW_STATUS.CUSTOMER_PO.REJECTED]: []
  },

  SALES_ORDER: {
    [WORKFLOW_STATUS.SALES_ORDER.DRAFT]: [
      WORKFLOW_STATUS.SALES_ORDER.CONFIRMED,
      WORKFLOW_STATUS.SALES_ORDER.CANCELLED
    ],
    [WORKFLOW_STATUS.SALES_ORDER.CONFIRMED]: [
      WORKFLOW_STATUS.SALES_ORDER.PAYMENT_PENDING,
      WORKFLOW_STATUS.SALES_ORDER.RELEASED_TO_PRODUCTION,
      WORKFLOW_STATUS.SALES_ORDER.CANCELLED
    ],
    [WORKFLOW_STATUS.SALES_ORDER.PAYMENT_PENDING]: [
      WORKFLOW_STATUS.SALES_ORDER.RELEASED_TO_PRODUCTION,
      WORKFLOW_STATUS.SALES_ORDER.CANCELLED
    ],
    [WORKFLOW_STATUS.SALES_ORDER.RELEASED_TO_PRODUCTION]: [
      WORKFLOW_STATUS.SALES_ORDER.IN_PRODUCTION,
      WORKFLOW_STATUS.SALES_ORDER.CANCELLED
    ],
    [WORKFLOW_STATUS.SALES_ORDER.IN_PRODUCTION]: [
      WORKFLOW_STATUS.SALES_ORDER.QA_IN_PROGRESS,
      WORKFLOW_STATUS.SALES_ORDER.CANCELLED
    ],
    [WORKFLOW_STATUS.SALES_ORDER.QA_IN_PROGRESS]: [
      WORKFLOW_STATUS.SALES_ORDER.READY_FOR_DISPATCH,
      WORKFLOW_STATUS.SALES_ORDER.IN_PRODUCTION
    ],
    [WORKFLOW_STATUS.SALES_ORDER.READY_FOR_DISPATCH]: [
      WORKFLOW_STATUS.SALES_ORDER.DISPATCHED
    ],
    [WORKFLOW_STATUS.SALES_ORDER.DISPATCHED]: [
      WORKFLOW_STATUS.SALES_ORDER.DELIVERED
    ],
    [WORKFLOW_STATUS.SALES_ORDER.DELIVERED]: [
      WORKFLOW_STATUS.SALES_ORDER.COMPLETED
    ],
    [WORKFLOW_STATUS.SALES_ORDER.COMPLETED]: [],
    [WORKFLOW_STATUS.SALES_ORDER.CANCELLED]: []
  },

  PRODUCTION_ORDER: {
    [WORKFLOW_STATUS.PRODUCTION_ORDER.PLANNED]: [
      WORKFLOW_STATUS.PRODUCTION_ORDER.RELEASED,
      WORKFLOW_STATUS.PRODUCTION_ORDER.CANCELLED
    ],
    [WORKFLOW_STATUS.PRODUCTION_ORDER.RELEASED]: [
      WORKFLOW_STATUS.PRODUCTION_ORDER.MATERIAL_REQUESTED,
      WORKFLOW_STATUS.PRODUCTION_ORDER.MATERIAL_READY,
      WORKFLOW_STATUS.PRODUCTION_ORDER.ON_HOLD,
      WORKFLOW_STATUS.PRODUCTION_ORDER.CANCELLED
    ],
    [WORKFLOW_STATUS.PRODUCTION_ORDER.MATERIAL_REQUESTED]: [
      WORKFLOW_STATUS.PRODUCTION_ORDER.MATERIAL_READY,
      WORKFLOW_STATUS.PRODUCTION_ORDER.ON_HOLD
    ],
    [WORKFLOW_STATUS.PRODUCTION_ORDER.MATERIAL_READY]: [
      WORKFLOW_STATUS.PRODUCTION_ORDER.IN_PROGRESS,
      WORKFLOW_STATUS.PRODUCTION_ORDER.FABRICATION
    ],
    [WORKFLOW_STATUS.PRODUCTION_ORDER.IN_PROGRESS]: [
      WORKFLOW_STATUS.PRODUCTION_ORDER.FABRICATION,
      WORKFLOW_STATUS.PRODUCTION_ORDER.REFRIGERATION,
      WORKFLOW_STATUS.PRODUCTION_ORDER.ELECTRICAL,
      WORKFLOW_STATUS.PRODUCTION_ORDER.ASSEMBLY,
      WORKFLOW_STATUS.PRODUCTION_ORDER.COMPLETED,
      WORKFLOW_STATUS.PRODUCTION_ORDER.ON_HOLD
    ],
    [WORKFLOW_STATUS.PRODUCTION_ORDER.FABRICATION]: [
      WORKFLOW_STATUS.PRODUCTION_ORDER.REFRIGERATION,
      WORKFLOW_STATUS.PRODUCTION_ORDER.ON_HOLD
    ],
    [WORKFLOW_STATUS.PRODUCTION_ORDER.REFRIGERATION]: [
      WORKFLOW_STATUS.PRODUCTION_ORDER.ELECTRICAL,
      WORKFLOW_STATUS.PRODUCTION_ORDER.ON_HOLD
    ],
    [WORKFLOW_STATUS.PRODUCTION_ORDER.ELECTRICAL]: [
      WORKFLOW_STATUS.PRODUCTION_ORDER.ASSEMBLY,
      WORKFLOW_STATUS.PRODUCTION_ORDER.ON_HOLD
    ],
    [WORKFLOW_STATUS.PRODUCTION_ORDER.ASSEMBLY]: [
      WORKFLOW_STATUS.PRODUCTION_ORDER.COMPLETED,
      WORKFLOW_STATUS.PRODUCTION_ORDER.ON_HOLD
    ],
    [WORKFLOW_STATUS.PRODUCTION_ORDER.ON_HOLD]: [
      WORKFLOW_STATUS.PRODUCTION_ORDER.RELEASED,
      WORKFLOW_STATUS.PRODUCTION_ORDER.IN_PROGRESS,
      WORKFLOW_STATUS.PRODUCTION_ORDER.CANCELLED
    ],
    [WORKFLOW_STATUS.PRODUCTION_ORDER.COMPLETED]: [],
    [WORKFLOW_STATUS.PRODUCTION_ORDER.CANCELLED]: []
  },

  QA_INSPECTION: {
    [WORKFLOW_STATUS.QA_INSPECTION.PENDING]: [
      WORKFLOW_STATUS.QA_INSPECTION.IN_PROGRESS
    ],
    [WORKFLOW_STATUS.QA_INSPECTION.IN_PROGRESS]: [
      WORKFLOW_STATUS.QA_INSPECTION.PASSED,
      WORKFLOW_STATUS.QA_INSPECTION.FAILED
    ],
    [WORKFLOW_STATUS.QA_INSPECTION.FAILED]: [
      WORKFLOW_STATUS.QA_INSPECTION.REWORK_IN_PROGRESS,
      WORKFLOW_STATUS.QA_INSPECTION.SCRAPPED
    ],
    [WORKFLOW_STATUS.QA_INSPECTION.REWORK_IN_PROGRESS]: [
      WORKFLOW_STATUS.QA_INSPECTION.RETESTED
    ],
    [WORKFLOW_STATUS.QA_INSPECTION.RETESTED]: [
      WORKFLOW_STATUS.QA_INSPECTION.PASSED,
      WORKFLOW_STATUS.QA_INSPECTION.FAILED,
      WORKFLOW_STATUS.QA_INSPECTION.SCRAPPED
    ],
    [WORKFLOW_STATUS.QA_INSPECTION.PASSED]: [],
    [WORKFLOW_STATUS.QA_INSPECTION.SCRAPPED]: []
  },

  SERVICE_TICKET: {
    [WORKFLOW_STATUS.SERVICE_TICKET.OPEN]: [
      WORKFLOW_STATUS.SERVICE_TICKET.ASSIGNED,
      WORKFLOW_STATUS.SERVICE_TICKET.CANCELLED
    ],
    [WORKFLOW_STATUS.SERVICE_TICKET.ASSIGNED]: [
      WORKFLOW_STATUS.SERVICE_TICKET.IN_PROGRESS,
      WORKFLOW_STATUS.SERVICE_TICKET.CANCELLED
    ],
    [WORKFLOW_STATUS.SERVICE_TICKET.IN_PROGRESS]: [
      WORKFLOW_STATUS.SERVICE_TICKET.DIAGNOSED,
      WORKFLOW_STATUS.SERVICE_TICKET.WAITING_FOR_PARTS,
      WORKFLOW_STATUS.SERVICE_TICKET.FACTORY_RETURN
    ],
    [WORKFLOW_STATUS.SERVICE_TICKET.DIAGNOSED]: [
      WORKFLOW_STATUS.SERVICE_TICKET.REPAIRED,
      WORKFLOW_STATUS.SERVICE_TICKET.WAITING_FOR_PARTS,
      WORKFLOW_STATUS.SERVICE_TICKET.FACTORY_RETURN
    ],
    [WORKFLOW_STATUS.SERVICE_TICKET.WAITING_FOR_PARTS]: [
      WORKFLOW_STATUS.SERVICE_TICKET.IN_PROGRESS,
      WORKFLOW_STATUS.SERVICE_TICKET.REPAIRED
    ],
    [WORKFLOW_STATUS.SERVICE_TICKET.FACTORY_RETURN]: [
      WORKFLOW_STATUS.SERVICE_TICKET.IN_PROGRESS,
      WORKFLOW_STATUS.SERVICE_TICKET.REPAIRED
    ],
    [WORKFLOW_STATUS.SERVICE_TICKET.REPAIRED]: [
      WORKFLOW_STATUS.SERVICE_TICKET.TESTED
    ],
    [WORKFLOW_STATUS.SERVICE_TICKET.TESTED]: [
      WORKFLOW_STATUS.SERVICE_TICKET.CUSTOMER_SIGNOFF,
      WORKFLOW_STATUS.SERVICE_TICKET.IN_PROGRESS
    ],
    [WORKFLOW_STATUS.SERVICE_TICKET.CUSTOMER_SIGNOFF]: [
      WORKFLOW_STATUS.SERVICE_TICKET.CLOSED
    ],
    [WORKFLOW_STATUS.SERVICE_TICKET.CLOSED]: [],
    [WORKFLOW_STATUS.SERVICE_TICKET.CANCELLED]: []
  }
};

const validateStatusTransition = (entityName, currentStatus, nextStatus) => {
  const rules = TRANSITION_RULES[entityName];
  if (!rules) {
    return true; // No explicit transition table defined, allow
  }

  if (currentStatus === nextStatus) {
    return true; // Idempotent same-state
  }

  const allowedNext = rules[currentStatus] || [];
  if (!allowedNext.includes(nextStatus)) {
    throw ApiError.invalidWorkflowState(
      `Invalid workflow transition for ${entityName}: Cannot move from '${currentStatus}' to '${nextStatus}'. Allowed transitions: [${allowedNext.join(', ')}]`
    );
  }

  return true;
};

module.exports = {
  TRANSITION_RULES,
  validateStatusTransition
};
