const ROLES = {
  ADMIN: 'ADMIN',
  SALES: 'SALES',
  SALES_MANAGER: 'SALES_MANAGER',
  ACCOUNTS: 'ACCOUNTS',
  PURCHASE: 'PURCHASE',
  STORE: 'STORE',
  PRODUCTION: 'PRODUCTION',
  QA: 'QA',
  DISPATCH: 'DISPATCH',
  SERVICE_MANAGER: 'SERVICE_MANAGER',
  SERVICE_ENGINEER: 'SERVICE_ENGINEER',
  MANAGEMENT: 'MANAGEMENT',
  R_AND_D: 'R_AND_D'
};

module.exports = ROLES;
