const WORKFLOW_STATUS = {
  LEAD: {
    NEW: 'NEW',
    CONTACTED: 'CONTACTED',
    FOLLOW_UP: 'FOLLOW_UP',
    QUALIFIED: 'QUALIFIED',
    CONVERTED: 'CONVERTED',
    LOST: 'LOST'
  },
  ENQUIRY: {
    DRAFT: 'DRAFT',
    ACTIVE: 'ACTIVE',
    QUOTED: 'QUOTED',
    CLOSED: 'CLOSED'
  },
  QUOTATION: {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    SENT: 'SENT',
    NEGOTIATION: 'NEGOTIATION',
    REVISED: 'REVISED',
    ACCEPTED: 'ACCEPTED',
    EXPIRED: 'EXPIRED',
    LOST: 'LOST'
  },
  PROFORMA_INVOICE: {
    DRAFT: 'DRAFT',
    APPROVED: 'APPROVED',
    SENT: 'SENT',
    CONVERTED_TO_ORDER: 'CONVERTED_TO_ORDER',
    CANCELLED: 'CANCELLED'
  },
  CUSTOMER_PO: {
    RECEIVED: 'RECEIVED',
    PENDING_VERIFICATION: 'PENDING_VERIFICATION',
    VERIFIED: 'VERIFIED',
    MISMATCH_HOLD: 'MISMATCH_HOLD',
    REJECTED: 'REJECTED'
  },
  SALES_ORDER: {
    DRAFT: 'DRAFT',
    CONFIRMED: 'CONFIRMED',
    PAYMENT_PENDING: 'PAYMENT_PENDING',
    RELEASED_TO_PRODUCTION: 'RELEASED_TO_PRODUCTION',
    IN_PRODUCTION: 'IN_PRODUCTION',
    QA_IN_PROGRESS: 'QA_IN_PROGRESS',
    READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
    DISPATCHED: 'DISPATCHED',
    DELIVERED: 'DELIVERED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },
  PAYMENT: {
    PENDING: 'PENDING',
    PARTIAL: 'PARTIAL',
    RECEIVED: 'RECEIVED',
    VERIFIED: 'VERIFIED',
    FAILED: 'FAILED',
    REVERSED: 'REVERSED',
    REFUNDED: 'REFUNDED'
  },
  PRODUCTION_ORDER: {
    PLANNED: 'PLANNED',
    RELEASED: 'RELEASED',
    MATERIAL_REQUESTED: 'MATERIAL_REQUESTED',
    MATERIAL_READY: 'MATERIAL_READY',
    IN_PROGRESS: 'IN_PROGRESS',
    FABRICATION: 'FABRICATION',
    REFRIGERATION: 'REFRIGERATION',
    ELECTRICAL: 'ELECTRICAL',
    ASSEMBLY: 'ASSEMBLY',
    COMPLETED: 'COMPLETED',
    ON_HOLD: 'ON_HOLD',
    CANCELLED: 'CANCELLED'
  },
  BOM: {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    ACTIVE: 'ACTIVE',
    REVISED: 'REVISED',
    OBSOLETE: 'OBSOLETE'
  },
  MATERIAL_REQUEST: {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    APPROVED: 'APPROVED',
    STOCK_CHECKED: 'STOCK_CHECKED',
    PARTIALLY_ISSUED: 'PARTIALLY_ISSUED',
    FULLY_ISSUED: 'FULLY_ISSUED',
    CANCELLED: 'CANCELLED'
  },
  PURCHASE_REQUEST: {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    RFQ_CREATED: 'RFQ_CREATED',
    PO_CREATED: 'PO_CREATED',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED'
  },
  RFQ: {
    DRAFT: 'DRAFT',
    SENT: 'SENT',
    QUOTATIONS_RECEIVED: 'QUOTATIONS_RECEIVED',
    COMPARED: 'COMPARED',
    VENDOR_SELECTED: 'VENDOR_SELECTED',
    CLOSED: 'CLOSED'
  },
  VENDOR_PO: {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    SENT: 'SENT',
    PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
    FULLY_RECEIVED: 'FULLY_RECEIVED',
    CANCELLED: 'CANCELLED'
  },
  GRN: {
    DRAFT: 'DRAFT',
    INSPECTED: 'INSPECTED',
    ACCEPTED: 'ACCEPTED',
    PARTIAL_ACCEPTED: 'PARTIAL_ACCEPTED',
    REJECTED: 'REJECTED'
  },
  QA_INSPECTION: {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    PASSED: 'PASSED',
    FAILED: 'FAILED',
    REWORK_IN_PROGRESS: 'REWORK_IN_PROGRESS',
    RETESTED: 'RETESTED',
    SCRAPPED: 'SCRAPPED'
  },
  PACKING: {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    PACKED: 'PACKED',
    READY_FOR_DISPATCH: 'READY_FOR_DISPATCH'
  },
  DISPATCH: {
    PREPARED: 'PREPARED',
    DISPATCHED: 'DISPATCHED',
    IN_TRANSIT: 'IN_TRANSIT',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
    DELIVERED: 'DELIVERED',
    FAILED: 'FAILED',
    RETURNED: 'RETURNED'
  },
  INSTALLATION: {
    PENDING: 'PENDING',
    ASSIGNED: 'ASSIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    TESTING: 'TESTING',
    COMMISSIONED: 'COMMISSIONED',
    FAILED: 'FAILED'
  },
  WARRANTY: {
    PENDING: 'PENDING',
    ACTIVE: 'ACTIVE',
    EXPIRED: 'EXPIRED',
    VOID: 'VOID'
  },
  SERVICE_TICKET: {
    OPEN: 'OPEN',
    ASSIGNED: 'ASSIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    DIAGNOSED: 'DIAGNOSED',
    WAITING_FOR_PARTS: 'WAITING_FOR_PARTS',
    FACTORY_RETURN: 'FACTORY_RETURN',
    REPAIRED: 'REPAIRED',
    TESTED: 'TESTED',
    CUSTOMER_SIGNOFF: 'CUSTOMER_SIGNOFF',
    CLOSED: 'CLOSED',
    CANCELLED: 'CANCELLED'
  },
  RMA: {
    REQUESTED: 'REQUESTED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    RECEIVED: 'RECEIVED',
    INSPECTING: 'INSPECTING',
    REPAIRING: 'REPAIRING',
    REPLACED: 'REPLACED',
    CREDITED: 'CREDITED',
    REFUNDED: 'REFUNDED',
    REDISPATCHED: 'REDISPATCHED',
    CLOSED: 'CLOSED'
  },
  RND_PROJECT: {
    PROPOSED: 'PROPOSED',
    APPROVED: 'APPROVED',
    IN_PROGRESS: 'IN_PROGRESS',
    TESTING: 'TESTING',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },
  EQUIPMENT_MAINTENANCE: {
    SCHEDULED: 'SCHEDULED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    OVERDUE: 'OVERDUE'
  }
};

module.exports = WORKFLOW_STATUS;
